Title-Component-Changes-with-styles-and-policies
ashankarprakash/aemaacsdemowebsite pull request #2
Opened 2023-04-04 20:28 UTC by ashankarprakash

2023-04-05 19:26 UTC, azouaoui-deloitte requested changes
There is a new conf folder not in the right place,
The policies are not persisted in the right place in the repository, when I build the project I don't see your changes,
You need to put your policies under ui.content/src/main/content/jcr_root/conf/aemaacsdemowebsite/settings/wcm/policies/.content.xml

2023-04-05 19:26 UTC, azouaoui-deloitte commented on conf/aemaacsdemowebsite/settings/wcm/policies/.content.xml
> +            <text/>
this is the result of a copy paste from a package coming from CRX, you need to commit only the changes (policies) you need

2023-04-05 19:39 UTC, manpkaur9 commented on ui.frontend/src/main/webpack/components/_title.scss
> +@media only screen and (max-width: 767px) {
Variable can be used here

2023-04-05 19:41 UTC, manpkaur9 commented on ui.frontend/src/main/webpack/components/_title.scss
> +    .headline-one{
also can be handled within line 5 block

2023-04-05 19:42 UTC, manpkaur9 commented on ui.frontend/src/main/webpack/components/_title.scss
> +    .headline-one{
.headline-one{
    font-size: 60px;
    @media only screen and (max-width: 767px) {
          font-size: 48px;
    }
}

2023-04-11 16:14 UTC, ashankarprakash commented on conf/aemaacsdemowebsite/settings/wcm/policies/.content.xml
> +            <text/>
Changes made in the recent commit.

2023-04-11 16:15 UTC, ashankarprakash commented on ui.frontend/src/main/webpack/components/_title.scss
> +@media only screen and (max-width: 767px) {
Changes made in the recent commit.

2023-04-11 16:15 UTC, ashankarprakash commented on ui.frontend/src/main/webpack/components/_title.scss
> +    .headline-one{
Changes made in the recent commit.

2023-04-11 18:11 UTC, azouaoui-deloitte commented on ui.content/src/main/content/jcr_root/conf/aemaacsdemowebsite/settings/wcm/policies/.content.xml
> +                    cq:styleDefaultClasses="heading-sizes"
Why did we add this default class? is it used somewhere?

2023-04-11 18:29 UTC, azouaoui-deloitte approved these changes

2023-04-18 17:45 UTC, merged