Container-Component-Style-and-policies
ashankarprakash/aemaacsdemowebsite pull request #3
Opened 2023-04-04 20:30 UTC by ashankarprakash

2023-04-05 13:43 UTC, manpkaur9 requested changes

2023-04-05 15:57 UTC, manpkaur9 requested changes

2023-04-05 15:57 UTC, manpkaur9 commented on conf/aemaacsdemowebsite/settings/wcm/policies/.content.xml
> +                <policy_3788240591800
I see the policy created here, but I do not see that used in template

2023-04-05 15:57 UTC, manpkaur9 commented on conf/.content.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Wrong location, you are not supposed to create a conf module here

2023-04-05 15:57 UTC, manpkaur9 commented on conf/aemaacsdemowebsite/.content.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Wrong location, you are not supposed to create a conf module here

2023-04-05 15:57 UTC, manpkaur9 commented on conf/aemaacsdemowebsite/settings/.content.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Wrong location, you are not supposed to create a conf module here

2023-04-05 15:57 UTC, manpkaur9 commented on conf/aemaacsdemowebsite/settings/wcm/.content.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Wrong location, you are not supposed to create a conf module here

2023-04-05 15:57 UTC, manpkaur9 commented on conf/aemaacsdemowebsite/settings/wcm/policies/.content.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Wrong location, you are not supposed to create a conf module here

2023-04-05 19:28 UTC, azouaoui-deloitte requested changes
same comments for the other PR (wrong location )

2023-04-06 17:11 UTC, ashankarprakash commented
https://becurious.edcast.eu/journey/aem-demo-website/cards/109701769 
The container card.

2023-04-06 18:59 UTC, azouaoui-deloitte commented on ui.content/src/main/content/jcr_root/conf/aemaacsdemowebsite/settings/wcm/templates/page-content/policies/.content.xml
> +                <container
it's not the right place,
Did you build the branch before sending the PR?

2023-04-06 19:15 UTC, azouaoui-deloitte requested changes

2023-04-06 19:15 UTC, azouaoui-deloitte commented on ui.content/src/main/content/jcr_root/conf/aemaacsdemowebsite/settings/wcm/templates/page-content/policies/.content.xml
> +                <container
it's the wrong place :/ it needs to be under  <container><aemaacsdemowebsite> <components>

2023-04-06 19:45 UTC, manpkaur9 commented
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>
<!--StartFragment-->

<div style='direction:ltr'>


1. Style   options for width are not available
2. Style   options for vertical padding are not available
3. No   option available for padding none, only left padding is there, no right, top   and bottom
4. Text   color should change on selection of background color itself. No need to   create it as separate style option. Please rename the background color   options in style system as per author requirement



</div>

<!--EndFragment-->
</body>

</html>

2023-04-10 17:21 UTC, ashankarprakash commented on ui.content/src/main/content/jcr_root/conf/aemaacsdemowebsite/settings/wcm/templates/page-content/policies/.content.xml
> +                <container
Issue resolved in the latest commit.

2023-04-10 17:21 UTC, ashankarprakash commented on ui.content/src/main/content/jcr_root/conf/aemaacsdemowebsite/settings/wcm/templates/page-content/policies/.content.xml
> +                                cq:policy="aemaacsdemowebsite/components/title/policy_3788240591800"
Issue resolved in the latest commit.

2023-04-10 20:24 UTC, manpkaur9 commented on ui.content/src/main/content/jcr_root/conf/aemaacsdemowebsite/settings/wcm/policies/.content.xml
>                      jcr:lastModifiedBy="admin"
jcr:lastModified, jcr:lastModifiedBy need not be committed

2023-04-10 20:59 UTC, manpkaur9 commented on ui.content/src/main/content/jcr_root/conf/aemaacsdemowebsite/settings/wcm/policies/.content.xml
>                                      jcr:primaryType="nt:unstructured"/>
As an author, I can select the vertical padding of the Container via the style system.

1. None
2. Default Padding (64px)

2023-04-10 21:01 UTC, manpkaur9 commented on ui.content/src/main/content/jcr_root/conf/aemaacsdemowebsite/settings/wcm/policies/.content.xml
> +                            </cq:styles>
Transparent option is missing

2023-04-11 13:30 UTC, ashankarprakash commented on ui.content/src/main/content/jcr_root/conf/aemaacsdemowebsite/settings/wcm/policies/.content.xml
>                                      jcr:primaryType="nt:unstructured"/>
Added in the latest commit.

2023-04-11 20:42 UTC, azouaoui-deloitte commented on ui.frontend/src/main/webpack/site/_variables.scss
> +$color-transparent: black;
do we want the background black or transparent?
The acceptance criteria says:

> As an author, I can select the background color of the Container via the style system. The text color should change from black to white depending on the background color. 

> - Transparent (Black Text)

2023-04-11 20:45 UTC, azouaoui-deloitte commented on ui.frontend/src/main/webpack/site/_variables.scss
> +$color-transparent: black;
with your code, the background is black, and the text is black, so we're not able to see the text and read it.
Have you tested this acceptance criteria as mentioned in the 3 bullet points?

2023-04-11 20:46 UTC, ashankarprakash commented on ui.frontend/src/main/webpack/site/_variables.scss
> +$color-transparent: black;
@azouaoui-deloitte if background is black then the text should be white, but it has been mentioned that we need Transparent (Black Text). I assume the background color should be nothing but have the texts in black since it mentions black text.

2023-04-11 20:48 UTC, ashankarprakash commented on ui.frontend/src/main/webpack/site/_variables.scss
> +$color-transparent: black;
@azouaoui-deloitte it mentions that the text color should change to black or white based on the options provided in the brackets, I assume the criteria is for all the background colors and not just the first one.

2023-04-11 20:57 UTC, azouaoui-deloitte commented
same here, I've tested the white background and the text is not black as mentioned in the acceptance criteria 
<img width="1284" alt="Capture d’écran, le 2023-04-11 à 16 57 36" src="https://user-images.githubusercontent.com/77859905/231286425-493e5704-0842-4eb8-a358-2cf62d19dc6a.png">

2023-04-11 21:12 UTC, azouaoui-deloitte commented on ui.frontend/src/main/webpack/site/_variables.scss
> +$color-transparent: black;
it says, we want a transparent background, not a black background 
in case you didn't find how to here is a link that **might** help you
https://stackoverflow.com/questions/11807286/how-to-make-div-background-color-transparent-in-css

2023-04-11 22:24 UTC, manpkaur9 commented on ui.frontend/src/main/webpack/components/_container.scss
> +.text-white{
Unused/dead code

2023-04-11 23:11 UTC, manpkaur9 commented
Selecting padding as none for either vertical or horizontal padding strips of the existing padding for the later

2023-04-12 19:06 UTC, manpkaur9 approved these changes

2023-04-19 19:07 UTC, ashankarprakash commented on ui.frontend/src/main/webpack/components/_container.scss
> +        width: $width-contained !important;
Resolved issue.

2023-04-19 19:07 UTC, ashankarprakash commented on ui.content/src/main/content/jcr_root/conf/aemaacsdemowebsite/settings/wcm/policies/.content.xml
> +                                    cq:styleLabel="Transparent (Black Text) "
Removed in latest commit.

2023-04-19 19:07 UTC, ashankarprakash commented on ui.content/src/main/content/jcr_root/conf/aemaacsdemowebsite/settings/wcm/policies/.content.xml
> +                                    cq:styleLabel="None "
Removed in latest commit.

2023-04-21 10:36 UTC, jfgrenier-inm commented on ui.frontend/src/main/webpack/components/_container.scss
>          width: $width-contained;
Max-width was meant to replace the width: $width-contained... not the media query

2023-05-03 19:42 UTC, jfgrenier-inm approved these changes

2023-05-03 19:48 UTC, merged