Button-components-changes-https://becurious.edcast.eu/journey/aem-demo-website/cards/109701819
ashankarprakash/aemaacsdemowebsite pull request #5
Opened 2023-04-17 14:34 UTC by ashankarprakash

2023-04-17 15:14 UTC, manpkaur9 commented on ui.content/src/main/content/jcr_root/conf/aemaacsdemowebsite/settings/wcm/policies/.content.xml
> +                    jcr:lastModified="{Date}2023-04-13T06:09:02.574-04:00"
Please remove these fields, same comment as last PR

2023-04-17 15:15 UTC, manpkaur9 commented on ui.frontend/src/main/webpack/site/_variables.scss
> +$button-alignment-left: left;
unnecessary variables for inherit, left, right and center

2023-04-17 15:21 UTC, manpkaur9 requested changes
<img width="1369" alt="image" src="https://user-images.githubusercontent.com/104098543/232533399-d543c1bc-b0da-42ab-9c83-752710f1e5f8.png">


The styles are not working as expected

2023-04-17 15:31 UTC, manpkaur9 requested changes
<img width="588" alt="image" src="https://user-images.githubusercontent.com/104098543/232536153-eb3b62a7-0d01-4438-a7a1-0392350da5b0.png">

Also, there is this difference between the two buttons

2023-04-18 13:26 UTC, ashankarprakash commented on ui.content/src/main/content/jcr_root/conf/aemaacsdemowebsite/settings/wcm/policies/.content.xml
> +            <button jcr:primaryType="nt:unstructured">
Added in the latest commit.

2023-04-18 13:27 UTC, ashankarprakash commented on ui.content/src/main/content/jcr_root/conf/aemaacsdemowebsite/settings/wcm/policies/.content.xml
> +                    jcr:lastModified="{Date}2023-04-13T06:09:02.574-04:00"
Removed in the latest commit.

2023-04-18 13:27 UTC, ashankarprakash commented on ui.frontend/src/main/webpack/site/_variables.scss
> +$button-alignment-left: left;
Removed in the latest commit.

2023-04-18 17:43 UTC, manpkaur9 approved these changes

2023-04-28 19:43 UTC, merged